version: 2
updates:
  - package-ecosystem: npm
    directory: '/web'
    schedule:
      interval: daily
    target-branch: 'vNext'
  - package-ecosystem: nuget
    directory: '/api'
    schedule:
      interval: daily
    target-branch: 'vNext'
