name: FilterLists Web Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - vNext
    paths:
      - web/**
      - api/**
      - .github/workflows/filterlists-web-azure-static-web-app.yml
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - vNext
    paths:
      - web/**
      - api/**
      - .github/workflows/filterlists-web-azure-static-web-app.yml

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Publish API
        working-directory: ./api
        run: dotnet publish -c Release -r win-x86 -p:PublishReadyToRun=true --no-self-contained

      - name: Build app and deploy SWA
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.FILTERLISTS_WEB_AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/web'
          output_location: '/dist/apps/web'
          skip_api_build: true
          api_location: '/api/bin/Release/net6.0/win-x86/publish'

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Remove SWA staging for PR
    runs-on: ubuntu-latest
    steps:
      - name: Close PR
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.FILTERLISTS_WEB_AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'close'
